name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort pytest mypy
          pip install types-PyJWT
          pip install pytest-cov

      - name: Check code formatting with Black
        run: |
          black . --check

      - name: Check imports with isort
        run: |
          isort . --check-only

      - name: Type check with mypy
        run: |
          mypy .

      - name: Run tests
        run: |
          cd tests
          pytest --cov=src --cov-report=xml
        env:
          JWT_SECRET: "test"
          JWT_ALGORITHM: "HS256"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
